#!/bin/bash

IP_ADDRESS=127.0.0.1
BASE_DIR=${HOME}/testnet-net

#ETH2_TESTNET_GENESIS_PATH=/home/andy/Source/work/historical-sync-debug/tools/eth2-testnet-genesis/eth2-testnet-genesis

#REHT_PATH=/home/andy/Source/work/reth/target/debug/reth
#LIGHTHOUSE_PATH=/home/andy/Tools/lighthouse/lighthouse

CONFIGS_PATH=$BASE_DIR/network-configs
JWT_PATH=$BASE_DIR/jwt
KEYSTORE_PATH=$BASE_DIR/ks
NODE_0_KEYSTORES_PATH=$KEYSTORE_PATH/node-0-keystores
NODE_1_KEYSTORES_PATH=$KEYSTORE_PATH/node-1-keystores


EL_RETH_1_DATA_PATH=$BASE_DIR/data/reth1/execution-data
EL_RETH_2_DATA_PATH=$BASE_DIR/data/reth2/execution-data
EL_HISTORICAL_SYNC_DATA_PATH=$BASE_DIR/data/his-sync/execution-data


CL_LIGHTHOUSE_1_DATA_PATH=$BASE_DIR/data/lighthouse1/execution-data
CL_LIGHTHOUSE_2_DATA_PATH=$BASE_DIR/data/lighthouse2/execution-data

EL_RETH_1_HTTP_PORT=8545
EL_RETH_2_HTTP_PORT=9545
EL_RETH_SYNC_HTTP_PORT=7545

EL_RETH_1_WS_PORT=8546
EL_RETH_2_WS_PORT=9546

EL_RETH_1_AUTH_RPC_PORT=8551
EL_RETH_2_AUTH_RPC_PORT=9551
EL_RETH_SYNC_AUTH_RPC_PORT=7551

EL_RETH_1_METRICS_PORT=9001
EL_RETH_2_METRICS_PORT=8001

EL_RETH_1_PORT=30303
EL_RETH_2_PORT=50303
EL_RETH_SYNC_PORT=60303

CL_LIGHTHOUSE_1_ENR_UDP_PORT=9000
CL_LIGHTHOUSE_2_ENR_UDP_PORT=8000

CL_LIGHTHOUSE_1_ENR_TCP_PORT=9000
CL_LIGHTHOUSE_2_ENR_TCP_PORT=8000

CL_LIGHTHOUSE_1_PORT=9000
CL_LIGHTHOUSE_2_PORT=8000

CL_LIGHTHOUSE_1_HTTP_PORT=4000
CL_LIGHTHOUSE_2_HTTP_PORT=5000

CL_LIGHTHOUSE_1_METRICS_PORT=5054
CL_LIGHTHOUSE_2_METRICS_PORT=6064


VC_LIGHTHOUSE_1_METRICS_PORT=6080
VC_LIGHTHOUSE_2_METRICS_PORT=7080
