# This is a basic workflow to help you get started with Actions

name: CheckForHistoricalSync

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ action-debug ]
  pull_request:
    branches: [ action-debug ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checks-out substrate 
      - uses: actions/checkout@v2
        with: 
            path: ./reth         # later mega-reth 
            ref: action-debug    # later develop

      # Setup Go enviroment
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
              go-version: '1.21.4' # The Go version to download (if necessary) and use.

      # Install Jq 
      - name: Install Jq 
        uses: dcarbone/install-jq-action@main
        with:
              version: '1.6' # The Jq version to download (if necessary) and use.

      # Install Rust
      - name: Install Rust 
        uses: digitalnativeinc/install-rust-substrate-action@0.4.0

      # Install other tools 
      - name: Setup 
        run: |
            cd reth/testing/it-test/github-action
            ./setup.sh

      ## Run private testnet 
      #- name: Run testnet 
      #  run: |
      #      pwd
      #      cd reth/testing/it-test/github-action
      #      ./action.sh
